import {
  ShieldAlert,
  Leaf,
  Activity,
  Truck,
  ArrowLeftRight,
  ClipboardCheck,
} from "lucide-react";

/** Mesmos ícones/cores do app SafeMine (tiles Lucide, sem PNG recortada). */
export const modules = [
  {
    id: "seguranca",
    title: "Segurança",
    blurb:
      "Quase-acidentes, incidentes e condições inseguras — com gravidade, causa raiz e tratativas da IA.",
    Icon: ShieldAlert,
    color: "#E53935",
    gradient: "linear-gradient(145deg, #FF8A80 0%, #E53935 100%)",
    shadow: "rgba(229, 57, 53, 0.28)",
    borderClass: "border-mod-safety",
    glow: "rgba(229,57,53,0.15)",
  },
  {
    id: "ambiental",
    title: "Ambiental",
    blurb:
      "Vazamentos, derrames e impactos em mina a céu aberto, com criticidade e medidas corretivas.",
    Icon: Leaf,
    color: "#43A047",
    gradient: "linear-gradient(145deg, #81C784 0%, #2E7D32 100%)",
    shadow: "rgba(67, 160, 71, 0.28)",
    borderClass: "border-mod-env",
    glow: "rgba(67,160,71,0.15)",
  },
  {
    id: "ergonomia",
    title: "Ergonomia",
    blurb: "Riscos posturais e de posto de trabalho, com prioridade e recomendações preventivas.",
    Icon: Activity,
    color: "#8E24AA",
    gradient: "linear-gradient(145deg, #CE93D8 0%, #7B1FA2 100%)",
    shadow: "rgba(142, 36, 170, 0.28)",
    borderClass: "border-mod-ergo",
    glow: "rgba(142,36,170,0.15)",
  },
  {
    id: "veiculo",
    title: "Veículo",
    blurb: "Checklist diário com 11 itens (pneus, freios, luzes, EPI do veículo e mais).",
    Icon: Truck,
    color: "#1E88E5",
    gradient: "linear-gradient(145deg, #64B5F6 0%, #1565C0 100%)",
    shadow: "rgba(30, 136, 229, 0.28)",
    borderClass: "border-mod-vehicle",
    glow: "rgba(30,136,229,0.15)",
  },
  {
    id: "turno",
    title: "Passagem de Turno",
    blurb: "Continuidade entre turnos: pendências, equipamentos e supervisores sem perda de informação.",
    Icon: ArrowLeftRight,
    color: "#FB8C00",
    gradient: "linear-gradient(145deg, #FFB74D 0%, #EF6C00 100%)",
    shadow: "rgba(251, 140, 0, 0.28)",
    borderClass: "border-mod-shift",
    glow: "rgba(245,124,0,0.15)",
  },
  {
    id: "inspecao",
    title: "Inspeção",
    blurb: "Rotina, especial ou auditoria — conformidades, não conformidades e plano de ação.",
    Icon: ClipboardCheck,
    color: "#00897B",
    gradient: "linear-gradient(145deg, #4DB6AC 0%, #00695C 100%)",
    shadow: "rgba(0, 137, 123, 0.28)",
    borderClass: "border-mod-inspection",
    glow: "rgba(0,137,123,0.15)",
  },
];
