export const modules = [
  {
    id: "seguranca",
    title: "Segurança",
    blurb: "Quase-acidentes, incidentes e condições inseguras — com gravidade, causa raiz e tratativas da IA.",
    icon: "/icons/seguranca.png",
    borderClass: "border-mod-safety",
    glow: "rgba(229,57,53,0.15)",
  },
  {
    id: "ambiental",
    title: "Ambiental",
    blurb: "Vazamentos, derrames e impactos em mina a céu aberto, com criticidade e medidas corretivas.",
    icon: "/icons/ambiental.png",
    borderClass: "border-mod-env",
    glow: "rgba(67,160,71,0.15)",
  },
  {
    id: "ergonomia",
    title: "Ergonomia",
    blurb: "Riscos posturais e de posto de trabalho, com prioridade e recomendações preventivas.",
    icon: "/icons/ergonomia.png",
    borderClass: "border-mod-ergo",
    glow: "rgba(142,36,170,0.15)",
  },
  {
    id: "veiculo",
    title: "Veículo",
    blurb: "Checklist diário com 11 itens (pneus, freios, luzes, EPI do veículo e mais).",
    icon: "/icons/veiculo.png",
    borderClass: "border-mod-vehicle",
    glow: "rgba(30,136,229,0.15)",
  },
  {
    id: "turno",
    title: "Passagem de Turno",
    blurb: "Continuidade entre turnos: pendências, equipamentos e supervisores sem perda de informação.",
    icon: "/icons/turno.png",
    borderClass: "border-mod-shift",
    glow: "rgba(245,124,0,0.15)",
  },
  {
    id: "inspecao",
    title: "Inspeção",
    blurb: "Rotina, especial ou auditoria — conformidades, não conformidades e plano de ação.",
    icon: "/icons/inspecao.png",
    borderClass: "border-mod-inspection",
    glow: "rgba(0,137,123,0.15)",
  },
];
