import {
  ShieldAlert,
  Leaf,
  Activity,
  Truck,
  ArrowLeftRight,
  ClipboardList,
} from "lucide-react";

export const modules = [
  {
    id: "seguranca",
    title: "Segurança",
    blurb: "Quase-acidentes, incidentes e condições inseguras registrados em segundos.",
    Icon: ShieldAlert,
    bgClass: "bg-mod-safety/10",
    textClass: "text-mod-safety",
    borderClass: "border-mod-safety",
  },
  {
    id: "ambiental",
    title: "Ambiental",
    blurb: "Vazamentos, derrames e impactos ambientais com responsável e ação corretiva.",
    Icon: Leaf,
    bgClass: "bg-mod-env/10",
    textClass: "text-mod-env",
    borderClass: "border-mod-env",
  },
  {
    id: "ergonomia",
    title: "Ergonomia",
    blurb: "Riscos posturais e movimentação repetitiva por posto e função.",
    Icon: Activity,
    bgClass: "bg-mod-ergo/10",
    textClass: "text-mod-ergo",
    borderClass: "border-mod-ergo",
  },
  {
    id: "veiculo",
    title: "Veículo",
    blurb: "Checklist diário de equipamentos pesados em 11 itens críticos.",
    Icon: Truck,
    bgClass: "bg-mod-vehicle/10",
    textClass: "text-mod-vehicle",
    borderClass: "border-mod-vehicle",
  },
  {
    id: "turno",
    title: "Passagem de Turno",
    blurb: "Continuidade entre turnos sem perda de informação operacional.",
    Icon: ArrowLeftRight,
    bgClass: "bg-mod-shift/10",
    textClass: "text-mod-shift",
    borderClass: "border-mod-shift",
  },
  {
    id: "inspecao",
    title: "Inspeção",
    blurb: "Inspeções de rotina, especiais e auditorias com evidências em foto e voz.",
    Icon: ClipboardList,
    bgClass: "bg-mod-inspection/10",
    textClass: "text-mod-inspection",
    borderClass: "border-mod-inspection",
  },
];
